### ISSUE TITLE
Edge set of triangulation, in extreme cases, may not contain convex hull

### ISSUE THREAD

**Issue by jpardey** [jmespadero/pyDelaunay2D#3]
I've been working on a simple JS implementation of the Bowyer-Watson algorithm for a web graphics project. After running into an issue, I was hoping to find a solution in your code, but it seems to suffer from the same problem. This is something that will likely never occur in common use when the dummy triangle vertices are sufficiently far from the points being triangulated, but it might be worth noting.

As a simple example, the following set of inputs doesn't generate a triangle at all:

```
t=Delaunay2D(radius=100)
t.addPoint([75,90])
t.addPoint([80,80])
t.addPoint([90,75])
```
and exportDT returns
```
([array([75, 90]), array([80, 80]), array([90, 75])], [])
```

The necessary edge would in fact cross the edge between 80,80 and the super-triangle vertex at 100,100, so simply removing any triangle connected to said vertex would not generate the proper triangulation.

Adding a point at 90,90 causes it to output the more sensible
```
([array([75, 90]), array([80, 80]), array([90, 75]), array([90, 90])],
 [(3, 0, 1), (3, 1, 2)])
```
Likewise, [75,90], [90,90], [90,75] works fine.

I glanced through the Watson paper briefly, and it doesn't appear to make any mention of this. This may only occur when a dummy vertex occurs within the circumcircle of a triangle in the true Delaunay triangulation, but I think that would require some proving.

My project isn't at all critical to this kind of thing, and if it was I could use a larger super-triangle. Thanks for all the work you put into this, it's a great tool and educational resource!

**Comment by jmespadero** [comment]
Many thanks for your report. 

As you say, the problem is that the _superframe_ edges has to be far enough from input points. 
The recommended way to build it is to pre-compute the center of your input points and pass to the 
constructor, so the superframe is centered around your data instead of the default (0,0).
This "small modification" is working for me:

```python
from delaunay2D import Delaunay2D

t=Delaunay2D(center=(80,80), radius=100)
t.addPoint([75,90])
t.addPoint([80,80])
t.addPoint([90,75])
print (len(t.exportTriangles()), "Delaunay triangles")
print ("t.exportTriangles:", t.exportTriangles())
```

If you compute the center (the recommendation is to use _the center of the bounding box_) you can do the radius even smaller, as `t=Delaunay2D(center=(82.5,82.5), radius=25)`.

It is true that I could ask for the complete list of input points, compute their center and radius, and build a superframe that fits the input data, but I considered it was one step beyond of the minimal case.

**Comment by jpardey** [comment]
Thanks for the quick reply! For sure, a larger radius will help, but in my testing, it appears that the problem is more often due to triangles in the (true theoretical) triangulation having a vertex of the frame within its circumcircle.

Obviously a contrived example, but even within a unit square and the default radius, it's possible to come up with a triangle that will not be triangulated, such as [1.0, 0], [0, 1.0], [0.49999, 0.4999]. Clearly, this kind of input wouldn't be encountered without malicious attempt. I believe this to be a fundamental issue with the algorithm, although nearly straight lines like that would be a sore spot for any triangulation or convex hull algorithm.

**Comment by jmespadero** [comment]
Yes, you can break the algorithm with degenerate triangles that have a huge circumcircle, or using a inadequate superframe. Just remember that this code is about learning, not being fast nor robust.
